erDiagram
    GALLERY {
        ObjectId _id
        string title
        string description
        string category
        string blobUrl
        string contentType
        int width
        int height
        int fileSize
        date createdAt
        date updatedAt
    }

    APPLICATION {
        ObjectId _id
        string name
        string email
        string phone
        string cpf
        string cep
        string city
        string state
        string pcd
        string pcdDescription
        date createdAt
    }

    SETTINGS {
        ObjectId _id
        string key
        string value
    }
